name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push ctxsh/base
    runs-on: ubuntu-latest
    steps:
      jobs:
  multi-builders:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push ctxsh/core
        uses: docker/build-push-action@v1
        with:
          context: .
          file: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ctxsh/core
          tag_with_ref: true
          tags:
            - ctxsh/core:latest
